- name: db
  desc: "Control Devel DB Only"
  children:
    - name: start
      desc: "Start devel db on localhost via docker."
      shell:
        - docker-compose --project-directory ./DB -f ./.docker/database.yml up
    - name: stop
      desc: "Stop devel db on localhost via docker."
      shell:
        - docker-compose --project-directory ./DB -f ./.docker/database.yml down
    - name: status
      desc: "Show status of devel db."
      shell:
        - docker-compose --project-directory ./DB -f ./.docker/database.yml ps
    - name: reset
      desc: "Wipe devel db data."
      shell: 
        - docker-compose --project-directory ./DB -f ./.docker/database.yml down -v
    - name: shell
      desc: "Grab a shell to psql"
      shell:
        - docker exec -ti blogdb-db psql -U blogdb blogdb
- name: build
  desc: "Build packages or containers."
  children:
    - name: mojo
      desc: "Build the mojolicious base container."
      shell:
        - docker build . -t symkat/mojo -f .docker/mojo.dockerfile
    - name: blogdb
      desc: "Build the blogdb app container."
      shell:
        - docker build . -t symkat/blogdb -f .docker/blogdb.dockerfile
